// Mocks generated by Mockito 5.4.6 from annotations
// in disoriza/test/features/auth/presentation/controllers/auth_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:typed_data' as _i7;

import 'package:disoriza/features/auth/data/models/user_model.dart' as _i5;
import 'package:disoriza/features/auth/domain/usecases/auth_usecase.dart'
    as _i2;
import 'package:fpdart/fpdart.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AuthUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthUsecase extends _i1.Mock implements _i2.AuthUsecase {
  MockAuthUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<Exception, _i5.UserModel>> checkSession() =>
      (super.noSuchMethod(
            Invocation.method(#checkSession, []),
            returnValue: _i3.Future<_i4.Either<Exception, _i5.UserModel>>.value(
              _i6.dummyValue<_i4.Either<Exception, _i5.UserModel>>(
                this,
                Invocation.method(#checkSession, []),
              ),
            ),
          )
          as _i3.Future<_i4.Either<Exception, _i5.UserModel>>);

  @override
  _i3.Future<_i4.Either<Exception, _i5.UserModel>> register({
    required String? name,
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#register, [], {
              #name: name,
              #email: email,
              #password: password,
            }),
            returnValue: _i3.Future<_i4.Either<Exception, _i5.UserModel>>.value(
              _i6.dummyValue<_i4.Either<Exception, _i5.UserModel>>(
                this,
                Invocation.method(#register, [], {
                  #name: name,
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Either<Exception, _i5.UserModel>>);

  @override
  _i3.Future<_i4.Either<Exception, _i5.UserModel>> login({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {#email: email, #password: password}),
            returnValue: _i3.Future<_i4.Either<Exception, _i5.UserModel>>.value(
              _i6.dummyValue<_i4.Either<Exception, _i5.UserModel>>(
                this,
                Invocation.method(#login, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Either<Exception, _i5.UserModel>>);

  @override
  _i3.Future<_i4.Either<Exception, void>> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i3.Future<_i4.Either<Exception, void>>.value(
              _i6.dummyValue<_i4.Either<Exception, void>>(
                this,
                Invocation.method(#logout, []),
              ),
            ),
          )
          as _i3.Future<_i4.Either<Exception, void>>);

  @override
  _i3.Future<_i4.Either<Exception, void>> resetPassword({
    required String? email,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [], {#email: email}),
            returnValue: _i3.Future<_i4.Either<Exception, void>>.value(
              _i6.dummyValue<_i4.Either<Exception, void>>(
                this,
                Invocation.method(#resetPassword, [], {#email: email}),
              ),
            ),
          )
          as _i3.Future<_i4.Either<Exception, void>>);

  @override
  _i3.Future<_i4.Either<Exception, _i5.UserModel>> editProfile({
    required String? uid,
    String? name,
    _i7.Uint8List? image,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#editProfile, [], {
              #uid: uid,
              #name: name,
              #image: image,
            }),
            returnValue: _i3.Future<_i4.Either<Exception, _i5.UserModel>>.value(
              _i6.dummyValue<_i4.Either<Exception, _i5.UserModel>>(
                this,
                Invocation.method(#editProfile, [], {
                  #uid: uid,
                  #name: name,
                  #image: image,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Either<Exception, _i5.UserModel>>);

  @override
  _i3.Future<_i4.Either<Exception, void>> changeEmail({
    required String? email,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#changeEmail, [], {#email: email}),
            returnValue: _i3.Future<_i4.Either<Exception, void>>.value(
              _i6.dummyValue<_i4.Either<Exception, void>>(
                this,
                Invocation.method(#changeEmail, [], {#email: email}),
              ),
            ),
          )
          as _i3.Future<_i4.Either<Exception, void>>);
}
