// Mocks generated by Mockito 5.4.6 from annotations
// in disoriza/test/features/komunitas/presentation/controllers/komunitas_search_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:typed_data' as _i7;

import 'package:disoriza/features/komunitas/data/models/comment_model.dart'
    as _i8;
import 'package:disoriza/features/komunitas/data/models/post_model.dart' as _i5;
import 'package:disoriza/features/komunitas/data/models/post_with_comment.dart'
    as _i9;
import 'package:disoriza/features/komunitas/domain/usecases/komunitas_usecase.dart'
    as _i2;
import 'package:fpdart/fpdart.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [KomunitasUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockKomunitasUsecase extends _i1.Mock implements _i2.KomunitasUsecase {
  MockKomunitasUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<Exception, List<_i5.PostModel>>> fetchAllPosts({
    bool? latest = false,
    int? max,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllPosts, [], {#latest: latest, #max: max}),
            returnValue:
                _i3.Future<_i4.Either<Exception, List<_i5.PostModel>>>.value(
                  _i6.dummyValue<_i4.Either<Exception, List<_i5.PostModel>>>(
                    this,
                    Invocation.method(#fetchAllPosts, [], {
                      #latest: latest,
                      #max: max,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<Exception, List<_i5.PostModel>>>);

  @override
  _i3.Future<_i4.Either<Exception, List<_i5.PostModel>>> fetchReportedPosts() =>
      (super.noSuchMethod(
            Invocation.method(#fetchReportedPosts, []),
            returnValue:
                _i3.Future<_i4.Either<Exception, List<_i5.PostModel>>>.value(
                  _i6.dummyValue<_i4.Either<Exception, List<_i5.PostModel>>>(
                    this,
                    Invocation.method(#fetchReportedPosts, []),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<Exception, List<_i5.PostModel>>>);

  @override
  _i3.Future<_i4.Either<Exception, List<_i5.PostModel>>> fetchAktivitas({
    required String? uid,
    required String? filter,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchAktivitas, [], {
              #uid: uid,
              #filter: filter,
            }),
            returnValue:
                _i3.Future<_i4.Either<Exception, List<_i5.PostModel>>>.value(
                  _i6.dummyValue<_i4.Either<Exception, List<_i5.PostModel>>>(
                    this,
                    Invocation.method(#fetchAktivitas, [], {
                      #uid: uid,
                      #filter: filter,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<Exception, List<_i5.PostModel>>>);

  @override
  _i3.Future<_i4.Either<Exception, List<_i5.PostModel>>> searchPost({
    required String? search,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchPost, [], {#search: search}),
            returnValue:
                _i3.Future<_i4.Either<Exception, List<_i5.PostModel>>>.value(
                  _i6.dummyValue<_i4.Either<Exception, List<_i5.PostModel>>>(
                    this,
                    Invocation.method(#searchPost, [], {#search: search}),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<Exception, List<_i5.PostModel>>>);

  @override
  _i3.Future<_i4.Either<Exception, void>> createPost({
    required String? title,
    required String? description,
    required String? uid,
    _i7.Uint8List? image,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createPost, [], {
              #title: title,
              #description: description,
              #uid: uid,
              #image: image,
            }),
            returnValue: _i3.Future<_i4.Either<Exception, void>>.value(
              _i6.dummyValue<_i4.Either<Exception, void>>(
                this,
                Invocation.method(#createPost, [], {
                  #title: title,
                  #description: description,
                  #uid: uid,
                  #image: image,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Either<Exception, void>>);

  @override
  _i3.Future<_i4.Either<Exception, void>> deletePost({
    required String? postId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deletePost, [], {#postId: postId}),
            returnValue: _i3.Future<_i4.Either<Exception, void>>.value(
              _i6.dummyValue<_i4.Either<Exception, void>>(
                this,
                Invocation.method(#deletePost, [], {#postId: postId}),
              ),
            ),
          )
          as _i3.Future<_i4.Either<Exception, void>>);

  @override
  _i3.Future<_i4.Either<Exception, void>> likePost({
    required String? uid,
    required String? postId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#likePost, [], {#uid: uid, #postId: postId}),
            returnValue: _i3.Future<_i4.Either<Exception, void>>.value(
              _i6.dummyValue<_i4.Either<Exception, void>>(
                this,
                Invocation.method(#likePost, [], {#uid: uid, #postId: postId}),
              ),
            ),
          )
          as _i3.Future<_i4.Either<Exception, void>>);

  @override
  _i3.Future<_i4.Either<Exception, void>> unlikePost({
    required String? uid,
    required String? postId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#unlikePost, [], {#uid: uid, #postId: postId}),
            returnValue: _i3.Future<_i4.Either<Exception, void>>.value(
              _i6.dummyValue<_i4.Either<Exception, void>>(
                this,
                Invocation.method(#unlikePost, [], {
                  #uid: uid,
                  #postId: postId,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Either<Exception, void>>);

  @override
  _i3.Future<_i4.Either<Exception, void>> reportPost({
    required String? uid,
    required String? postId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#reportPost, [], {#uid: uid, #postId: postId}),
            returnValue: _i3.Future<_i4.Either<Exception, void>>.value(
              _i6.dummyValue<_i4.Either<Exception, void>>(
                this,
                Invocation.method(#reportPost, [], {
                  #uid: uid,
                  #postId: postId,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Either<Exception, void>>);

  @override
  _i3.Future<_i4.Either<Exception, List<_i8.CommentModel>>> fetchComments({
    required String? postId,
    bool? latest = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchComments, [], {
              #postId: postId,
              #latest: latest,
            }),
            returnValue:
                _i3.Future<_i4.Either<Exception, List<_i8.CommentModel>>>.value(
                  _i6.dummyValue<_i4.Either<Exception, List<_i8.CommentModel>>>(
                    this,
                    Invocation.method(#fetchComments, [], {
                      #postId: postId,
                      #latest: latest,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<Exception, List<_i8.CommentModel>>>);

  @override
  _i3.Future<_i4.Either<Exception, List<_i9.PostWithCommentModel>>>
  fetchReportedComments() =>
      (super.noSuchMethod(
            Invocation.method(#fetchReportedComments, []),
            returnValue:
                _i3.Future<
                  _i4.Either<Exception, List<_i9.PostWithCommentModel>>
                >.value(
                  _i6.dummyValue<
                    _i4.Either<Exception, List<_i9.PostWithCommentModel>>
                  >(this, Invocation.method(#fetchReportedComments, [])),
                ),
          )
          as _i3.Future<_i4.Either<Exception, List<_i9.PostWithCommentModel>>>);

  @override
  _i3.Future<_i4.Either<Exception, void>> createComment({
    required _i8.CommentModel? comment,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createComment, [], {#comment: comment}),
            returnValue: _i3.Future<_i4.Either<Exception, void>>.value(
              _i6.dummyValue<_i4.Either<Exception, void>>(
                this,
                Invocation.method(#createComment, [], {#comment: comment}),
              ),
            ),
          )
          as _i3.Future<_i4.Either<Exception, void>>);

  @override
  _i3.Future<_i4.Either<Exception, void>> deleteComment({
    required String? commentId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteComment, [], {#commentId: commentId}),
            returnValue: _i3.Future<_i4.Either<Exception, void>>.value(
              _i6.dummyValue<_i4.Either<Exception, void>>(
                this,
                Invocation.method(#deleteComment, [], {#commentId: commentId}),
              ),
            ),
          )
          as _i3.Future<_i4.Either<Exception, void>>);

  @override
  _i3.Future<_i4.Either<Exception, void>> likeComment({
    required String? uid,
    required String? commentId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#likeComment, [], {
              #uid: uid,
              #commentId: commentId,
            }),
            returnValue: _i3.Future<_i4.Either<Exception, void>>.value(
              _i6.dummyValue<_i4.Either<Exception, void>>(
                this,
                Invocation.method(#likeComment, [], {
                  #uid: uid,
                  #commentId: commentId,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Either<Exception, void>>);

  @override
  _i3.Future<_i4.Either<Exception, void>> unlikeComment({
    required String? uid,
    required String? commentId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#unlikeComment, [], {
              #uid: uid,
              #commentId: commentId,
            }),
            returnValue: _i3.Future<_i4.Either<Exception, void>>.value(
              _i6.dummyValue<_i4.Either<Exception, void>>(
                this,
                Invocation.method(#unlikeComment, [], {
                  #uid: uid,
                  #commentId: commentId,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Either<Exception, void>>);

  @override
  _i3.Future<_i4.Either<Exception, void>> reportComment({
    required String? uid,
    required String? commentId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#reportComment, [], {
              #uid: uid,
              #commentId: commentId,
            }),
            returnValue: _i3.Future<_i4.Either<Exception, void>>.value(
              _i6.dummyValue<_i4.Either<Exception, void>>(
                this,
                Invocation.method(#reportComment, [], {
                  #uid: uid,
                  #commentId: commentId,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Either<Exception, void>>);
}
