// Mocks generated by Mockito 5.4.6 from annotations
// in disoriza/test/features/riwayat/presentation/controllers/riwayat_scan_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:convert' as _i8;
import 'dart:typed_data' as _i9;

import 'package:disoriza/features/riwayat/data/models/riwayat_model.dart'
    as _i5;
import 'package:disoriza/features/riwayat/domain/usecases/riwayat_usecase.dart'
    as _i2;
import 'package:fpdart/fpdart.dart' as _i4;
import 'package:image_picker/image_picker.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDateTime_0 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RiwayatUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRiwayatUsecase extends _i1.Mock implements _i2.RiwayatUsecase {
  MockRiwayatUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<Exception, List<_i5.RiwayatModel>>> fetchAllRiwayat({
    required String? uid,
    int? max,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllRiwayat, [], {#uid: uid, #max: max}),
            returnValue:
                _i3.Future<_i4.Either<Exception, List<_i5.RiwayatModel>>>.value(
                  _i6.dummyValue<_i4.Either<Exception, List<_i5.RiwayatModel>>>(
                    this,
                    Invocation.method(#fetchAllRiwayat, [], {
                      #uid: uid,
                      #max: max,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<Exception, List<_i5.RiwayatModel>>>);

  @override
  _i3.Future<_i4.Either<Exception, _i5.RiwayatModel?>> scanDisease({
    required String? uid,
    required _i7.XFile? image,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#scanDisease, [], {#uid: uid, #image: image}),
            returnValue:
                _i3.Future<_i4.Either<Exception, _i5.RiwayatModel?>>.value(
                  _i6.dummyValue<_i4.Either<Exception, _i5.RiwayatModel?>>(
                    this,
                    Invocation.method(#scanDisease, [], {
                      #uid: uid,
                      #image: image,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<Exception, _i5.RiwayatModel?>>);

  @override
  _i3.Future<_i4.Either<Exception, void>> deleteRiwayat({
    required String? riwayatId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRiwayat, [], {#riwayatId: riwayatId}),
            returnValue: _i3.Future<_i4.Either<Exception, void>>.value(
              _i6.dummyValue<_i4.Either<Exception, void>>(
                this,
                Invocation.method(#deleteRiwayat, [], {#riwayatId: riwayatId}),
              ),
            ),
          )
          as _i3.Future<_i4.Either<Exception, void>>);
}

/// A class which mocks [XFile].
///
/// See the documentation for Mockito's code generation for more information.
class MockXFile extends _i1.Mock implements _i7.XFile {
  MockXFile() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get path =>
      (super.noSuchMethod(
            Invocation.getter(#path),
            returnValue: _i6.dummyValue<String>(this, Invocation.getter(#path)),
          )
          as String);

  @override
  String get name =>
      (super.noSuchMethod(
            Invocation.getter(#name),
            returnValue: _i6.dummyValue<String>(this, Invocation.getter(#name)),
          )
          as String);

  @override
  _i3.Future<void> saveTo(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#saveTo, [path]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<int> length() =>
      (super.noSuchMethod(
            Invocation.method(#length, []),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<String> readAsString({
    _i8.Encoding? encoding = const _i8.Utf8Codec(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readAsString, [], {#encoding: encoding}),
            returnValue: _i3.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#readAsString, [], {#encoding: encoding}),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<_i9.Uint8List> readAsBytes() =>
      (super.noSuchMethod(
            Invocation.method(#readAsBytes, []),
            returnValue: _i3.Future<_i9.Uint8List>.value(_i9.Uint8List(0)),
          )
          as _i3.Future<_i9.Uint8List>);

  @override
  _i3.Stream<_i9.Uint8List> openRead([int? start, int? end]) =>
      (super.noSuchMethod(
            Invocation.method(#openRead, [start, end]),
            returnValue: _i3.Stream<_i9.Uint8List>.empty(),
          )
          as _i3.Stream<_i9.Uint8List>);

  @override
  _i3.Future<DateTime> lastModified() =>
      (super.noSuchMethod(
            Invocation.method(#lastModified, []),
            returnValue: _i3.Future<DateTime>.value(
              _FakeDateTime_0(this, Invocation.method(#lastModified, [])),
            ),
          )
          as _i3.Future<DateTime>);
}
